const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {SeedanceRuntime}=require('../src/seedance-runtime');
const {FlowCutBridge}=require('../../vendor/seedance-engine/flowcut-bridge');
const {reviewDirectory}=require('../src/video-review');
const {receiptPath}=require('../src/video-delivery');
function box(type,data){const b=Buffer.alloc(8);b.writeUInt32BE(data.length+8);b.write(type,4);return Buffer.concat([b,data]);}
const mp4=Buffer.concat([box('ftyp',Buffer.from('isom0000')),box('moov',Buffer.from('meta')),box('mdat',Buffer.from('frames'))]);
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'flowcut-delivery-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const task={id:'local',taskId:'remote',flowcutTaskId:'web-task',status:'success',tiktokAccountName:'shop',archiveDirectory:path.join(root,'publish'),productExternalId:'1736724718556382511',videoUrl:'https://fixture/video'};let fetches=0,refreshes=0;const runtime=new SeedanceRuntime({app:{getPath:()=>root},flowcutStore:{}});runtime.emit=()=>{};runtime.store={settings:{},getTask:()=>task,upsertTask:()=>{}};runtime.engine={refreshTaskResult:async()=>{refreshes++},recordTask:()=>{}};runtime.accountManager={session:()=>({fetch:async()=>{fetches++;return new Response(mp4,{headers:{'content-type':'video/mp4'}})}})};return {root,task,runtime,counts:()=>({fetches,refreshes})};}
test('concurrent download calls reserve before refresh and create exactly one file',async t=>{const f=fixture(t);const results=await Promise.allSettled([f.runtime.downloadTask(f.task),f.runtime.downloadTask(f.task)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.message,'这条任务正在下载');assert.deepEqual(f.counts(),{fetches:1,refreshes:1});assert.equal(fs.readdirSync(reviewDirectory(f.root,f.task.flowcutTaskId)).filter(x=>x.endsWith('.mp4')).length,1);});
test('delivery receipt survives lost task fields and a published/deleted video',async t=>{const f=fixture(t);const first=await f.runtime.downloadTask(f.task);fs.unlinkSync(first.destination);delete f.task.lastDownloadedAt;delete f.task.lastDownloadedPath;delete f.task.reviewDownload;f.task.archiveDirectory=path.join(f.root,'different');const second=await f.runtime.downloadTask(f.task);assert.equal(second.alreadyDelivered,true);assert.equal(fs.existsSync(second.destination),false);assert.deepEqual(f.counts(),{fetches:1,refreshes:1});});
test('legacy approval stops download even without delivery fields or remaining file',async t=>{const f=fixture(t);const folder=reviewDirectory(f.root,f.task.flowcutTaskId);fs.mkdirSync(folder,{recursive:true});const file=path.join(f.root,'already-published.mp4');fs.writeFileSync(path.join(folder,'approval.json'),JSON.stringify({status:'released',file,approvedAt:'2026-10-03T00:00:00Z'}));const r=await f.runtime.downloadTask(f.task);assert.equal(r.alreadyDelivered,true);assert.equal(r.destination,file);assert.deepEqual(f.counts(),{fetches:0,refreshes:0});});
test('a completed review file left by a crash is reused without another download',async t=>{const f=fixture(t);const folder=reviewDirectory(f.root,f.task.flowcutTaskId);fs.mkdirSync(folder,{recursive:true});const file=path.join(folder,'1736724718556382511.mp4');fs.writeFileSync(file,mp4);assert.equal((await f.runtime.downloadTask(f.task)).destination,file);assert.deepEqual(f.counts(),{fetches:0,refreshes:0});assert.ok(fs.existsSync(receiptPath(f.root,f.task)));});
test('corrupt delivery records fail closed instead of silently replaying',async t=>{const f=fixture(t),file=receiptPath(f.root,f.task);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,'broken');await assert.rejects(f.runtime.downloadTask(f.task),/阻止重复下载/);assert.equal(f.counts().fetches,0);});
test('legacy downloaded marker prevents automatic replay after archive directory changes',()=>{let downloads=0;const task={id:'local',flowcutTaskId:'web',status:'success',tiktokAccountName:'shop',lastDownloadedPath:'C:/old/video.mp4',lastDownloadedAt:123,archiveDirectory:'C:/new'};const bridge=new FlowCutBridge({store:{settings:{}},engine:{},downloadTask:async()=>downloads++});bridge.scheduleAutoDownload(task);assert.equal(downloads,0);});
test('failed fetch releases reservation and a later attempt can succeed',async t=>{const f=fixture(t),manager=f.runtime.accountManager;f.runtime.accountManager={session:()=>({fetch:async()=>{throw Error('offline')}})};await assert.rejects(f.runtime.downloadTask(f.task),/offline/);f.runtime.accountManager=manager;assert.ok((await f.runtime.downloadTask(f.task)).destination);assert.equal(f.counts().fetches,1);});
